### ISSUE TITLE
pdf is truncated to first page (using materials theme)

### ISSUE THREAD

**Issue by k-vaughn** [shauser/mkdocs-pdf-export-plugin#121]
I just installed this tool. Everything seems to be configured correctly, yet the individual PDF files are truncated to a single page (plus a blank pre-pended page if the file requires more than one page). If I use the combined mode, I get the combined result (i.e., each document presented in order - for one-page documents, the flow is as one would expect, but for documents requiring multiple pages, there is a blank page prepended and then only one page of the document provided.

I simplified my mkdocs.yml file (below) to be as simple as possible, but I still get the same results.

```yml
site_name: ITS Open Source Process
repo_url: https://github.com/k-vaughn/ITS-open-source
nav:
  - Front Matter:
    - Title Page: index.md
    - Notices: notices.md
    - Acknowledgements: acknowledgements.md
    - Foreword: foreword.md
    - Introduction: introduction.md
  - 1 General: general.md
  - 2 Overview: overview.md
  - 3 Commenter Responsibilities: commenter-responsibilities.md
  - 4 Contributor Responsibilities: contributor-responsibilities.md
  - 5 Maintainer Responsibilities: maintainer-responsibilities.md
  - 6 WG Responsibilities: wg-responsibilities.md
  - A Code of Conduct: code-of-conduct.md
  - B Documentation Conventions: documentation-conventions.md
  - C Coding Conventions: coding-conventions.md
site_url: https://github.com/k-vaughn/ITS-open-source
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://github.com/k-vaughn/ITS-open-source">ITS Open-Source Process</a> by <span property="cc:attributionName">NTCIP</span> is licensed under <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a></p>
theme:
  name: material
plugins:
  - pdf-export
```
